# Generated by Django 4.1.7 on 2023-03-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
