# Generated by Django 4.1.7 on 2023-03-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
