# Generated by Django 4.1.7 on 2023-03-13 10:10

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_alter_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default=None, upload_to='thumbnails'),
            preserve_default=False,
        ),
    ]
