# Generated by Django 4.1.7 on 2023-03-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_alter_image_thumbnails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnails',
        ),
    ]
