# Generated by Django 4.1.7 on 2023-03-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_alter_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnail',
        ),
    ]
