# Generated by Django 4.1.7 on 2023-03-13 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0015_remove_image_image_file_image_avatar_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='avatar_thumbnail',
            new_name='image_file',
        ),
    ]
