# Generated by Django 4.1.7 on 2023-03-13 20:53

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0016_rename_avatar_thumbnail_image_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
