# Generated by Django 4.1.7 on 2023-03-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0020_image_thumbnail_alter_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
