# Generated by Django 4.1.7 on 2023-03-14 11:21

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0022_remove_image_thumbnail_alter_image_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnai_file',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
