# Generated by Django 4.1.7 on 2023-03-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0023_image_thumbnai_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnai_file',
        ),
    ]
