# Generated by Django 4.1.7 on 2023-03-14 11:31

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0024_remove_image_thumbnai_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
