# Generated by Django 4.1.7 on 2023-03-14 11:39

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0025_alter_image_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail_medium',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
