# Generated by Django 4.1.7 on 2023-03-14 12:17

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0027_remove_image_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='thumbnail_medium',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='images'),
        ),
    ]
