# Generated by Django 4.1.7 on 2023-03-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0028_uploadedimage_thumbnail_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='image_file',
        ),
    ]
