# Generated by Django 4.1.7 on 2023-03-14 12:31

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0029_remove_uploadedimage_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='image_file',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='thumbnail_medium',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='media'),
        ),
    ]
