# Generated by Django 4.1.7 on 2023-03-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0030_uploadedimage_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image_file',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
