# Generated by Django 4.1.7 on 2023-03-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0031_alter_uploadedimage_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image_file',
            field=models.ImageField(default=None, null=True, upload_to='media'),
        ),
    ]
