# Generated by Django 4.1.7 on 2023-03-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0032_alter_uploadedimage_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='thumbnail_medium',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
