# Generated by Django 4.1.7 on 2023-03-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0033_remove_uploadedimage_image_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='image',
            new_name='image_file',
        ),
    ]
