# Generated by Django 4.1.7 on 2023-03-15 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0034_rename_image_uploadedimage_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='image_file',
            new_name='image',
        ),
    ]
