# Generated by Django 4.1.7 on 2023-03-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0036_uploadedimage_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.userprofile'),
        ),
    ]
