# Generated by Django 4.1.7 on 2023-03-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0038_alter_uploadedimage_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
