# Generated by Django 4.1.7 on 2023-03-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0039_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
