# Generated by Django 4.1.7 on 2023-03-22 12:54

from django.db import migrations, models
import protected_media.models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0040_uploadedimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='expiration_time',
            field=models.PositiveIntegerField(default=5, help_text='Expiration time in seconds'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=protected_media.models.ProtectedImageField(default=None, null=True, storage=protected_media.models.ProtectedFileSystemStorage(), upload_to='images/'),
        ),
    ]
