# Generated by Django 4.1.7 on 2023-03-23 10:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0043_expirationtime_alter_uploadedimage_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expirationtime',
            name='expiration_time',
            field=models.PositiveIntegerField(default=300, help_text='Expiration time in seconds', validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)]),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='expiration_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.expirationtime'),
        ),
    ]
