# Generated by Django 4.1.7 on 2023-03-23 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0044_alter_expirationtime_expiration_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('thumbnail_sizes', models.CharField(help_text="Comma-separated sizes (e.g., '200,400')", max_length=255)),
                ('access_original', models.BooleanField(default=False)),
                ('has_expiring_links', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_tier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.tier'),
        ),
    ]
