# Generated by Django 4.1.7 on 2023-03-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0045_tier_userprofile_custom_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(blank=True, choices=[('B', 'Basic'), ('P', 'Premium'), ('E', 'Enterprise')], max_length=1, null=True),
        ),
    ]
